name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |-
          This is a message, and you'll get it when you submit an issue for the first time!
          Your name is ${{ github.actor }}!
        
          This repo is ${{ github.repository }}!\n        
        
          Stay cool! And find our [contribution guidelines here](https://github.com/anchore/anchore-engine/blob/master/CONTRIBUTING.rst)!
        pr-message: 'Message that will be displayed on users'' first pr'
