name: Greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |-
          Hello ${{ github.actor }},

          Thank you for being part of the Anchore Engine community!

          ![Thank you](https://github.com/robertp/grip/raw/master/docs/keanu-thank-you.gif)

          An Anchorite will look at your issue soon. We also have great [documentation](https://docs.anchore.com/current/), including [FAQs](https://docs.anchore.com/current/docs/faq/) and [release notes](https://docs.anchore.com/current/docs/releasenotes/).

          You can also find our [contribution guidelines here](https://github.com/anchore/anchore-engine/blob/master/CONTRIBUTING.rst). Thank you again!
